language: clojure
lein: lein2
before_script:
  - lein2 test-server & # start the web server
  - sleep 45 # give the server time to start
  - /usr/local/phantomjs --version
script: lein2 test!
branches:
  only:
    - master
jdk:
  - oraclejdk7
services:
  - redis-server
notifications:
  hipchat:
    rooms:
      - ec1ead2b384476ea5bcb232b5bb9b6@Snooty Monkey